---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'

    - uses: timbertson/self-update-action@wip
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        branchName: test-add-date
        commitMessage: "Just adding the date..."
        prTitle: "[test] applyUpdate"
        prBody: "This is a test PR"
        updateScript: |-
          echo "Today is $(date)" > current-date
          git add --intent-to-add current-date

    - uses: timbertson/self-update-action@wip
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        branchName: test-add-date-2
        prTitle: "[test] applyUpdateScript"
        prBody: "This is a test PR"
        updateScript: |-
          echo "Today is $(date)" > current-date
          git add --intent-to-add current-date
        applyUpdateScript: |-
          sed -i -e 's/is .*/is [censored]/' current-date

    - uses: timbertson/self-update-action@wip
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        prTitle: "[test] unchanged"
        branchName: test-unchanged-apply
        updateScript: |-
          echo "Today is $(date)" > current-date
          git add --intent-to-add current-date
        applyUpdateScript: |-
          true

    - uses: timbertson/self-update-action@wip
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        prTitle: "[test] unchanged"
        branchName: test-unchanged-initial
        updateScript: |-
          true

    - uses: timbertson/self-update-action@wip
      continue-on-error: true
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        branchName: test-add-date-fail
        prTitle: "[test] simulated error"
        prBody: "This is a test PR"
        updateScript: |-
          echo "Uh oh..."
          exit 2

name: Self-update test
on:
  push:
    branches:
     - wip
  schedule:
    - cron: "*/5 * * * *" # every 5m
    # - cron: "0 0 * * 0" # every sunday
    # - cron: "0 2 * * *" # every day at 2am
